# specify python as the language
language: python
sudo: required

# python versions to be used for testing
python:
  - "2.7"

env:
  - JYTHON=true
  - JYTHON=false

matrix:
  exclude:
    - python: 2.7
      env: JYTHON=true

before_install: if [ "$JYTHON" == "true" ]; then sudo apt-get install jython; fi

before_script: if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi

script:
  - $PYTHON_EXE setup.py develop
  - xcat_app --test